modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/TheGreyGhost/ItemTransformHelper"
license = "All rights reserved"

[[mods]]
modId = "itemtransformhelper"
version = "${version}"
displayName = "Item Transform Helper"
authors = "TGG, ThexXTURBOXx, Romejanic, lehjr"
description = '''
Interactively change the position, scale, and rotation of an item.
'''

[[dependencies.itemtransformhelper]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "architectury"
mandatory = true
versionRange = "[5.6.22,)"
ordering = "AFTER"
side = "BOTH"
